
import React from 'react';
import { SpiritualMastery } from '../types';
import { Crown, Star, ShieldCheck, Waves, Compass } from 'lucide-react';

interface Props {
  mastery: SpiritualMastery;
  ascSign: string;
  imageUrl?: string;
}

const SpiritualMasteryCard: React.FC<Props> = ({ mastery, ascSign, imageUrl }) => {
  return (
    <div className="glass-panel p-8 rounded-[2.5rem] relative overflow-hidden border-yellow-500/30 shadow-[0_0_60px_rgba(234,179,8,0.15)] group">
      <div className="absolute top-0 right-0 p-10 opacity-5 rotate-12 transition-transform group-hover:rotate-0 duration-700">
        <Crown size={220} className="text-yellow-400" />
      </div>
      
      <div className="relative z-10 flex flex-col md:flex-row gap-10 items-center">
        {/* Master Photo Generated by AI */}
        <div className="w-64 h-80 rounded-[2rem] border-2 border-yellow-500/30 p-1 relative shrink-0 overflow-hidden shadow-2xl bg-black">
          {imageUrl ? (
            <img 
              src={imageUrl} 
              alt={mastery.masterName} 
              className="w-full h-full object-cover transition-transform duration-[10s] group-hover:scale-110"
            />
          ) : (
            <div className="w-full h-full bg-gradient-to-br from-yellow-900/40 to-black flex items-center justify-center">
              <Star size={40} className="text-yellow-500/20 animate-pulse" />
            </div>
          )}
          <div className="absolute inset-0 bg-gradient-to-t from-black/80 via-transparent to-transparent pointer-events-none"></div>
          <div className="absolute bottom-4 left-1/2 -translate-x-1/2 text-[10px] font-black text-yellow-500 uppercase tracking-[0.3em] whitespace-nowrap bg-black/60 px-4 py-1.5 rounded-full border border-yellow-500/20">
             Manifestación Sagrada
          </div>
        </div>

        <div className="flex-1 space-y-6">
          <div className="space-y-2">
            <div className="flex items-center gap-2">
                <span className="px-3 py-1 rounded-full bg-yellow-500/10 text-yellow-500 text-[10px] font-black uppercase tracking-widest border border-yellow-500/20">
                    Maestro Ascendido Regente
                </span>
            </div>
            <h3 className="cinzel text-5xl font-black text-white group-hover:text-yellow-400 transition-colors">{mastery.masterName}</h3>
            <p className="text-yellow-200/60 font-medium tracking-wide text-lg">{mastery.ashramWork}</p>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
              <div className="p-4 rounded-2xl bg-white/5 border border-white/10 flex items-center gap-4 group-hover:bg-white/10 transition-all">
                  <div className="w-10 h-10 rounded-full bg-purple-500/20 flex items-center justify-center text-purple-400">
                      <Compass size={20} />
                  </div>
                  <div>
                      <div className="text-[10px] text-gray-500 uppercase tracking-tighter">Portal Ascendente</div>
                      <div className="text-lg font-bold text-white cinzel">{ascSign}</div>
                  </div>
              </div>
              <div className="p-4 rounded-2xl bg-white/5 border border-white/10 flex items-center gap-4 group-hover:bg-white/10 transition-all">
                  <div className="w-10 h-10 rounded-full bg-yellow-500/20 flex items-center justify-center text-yellow-500">
                      <Waves size={20} />
                  </div>
                  <div>
                      <div className="text-[10px] text-gray-500 uppercase tracking-tighter">Vibración del Alma</div>
                      <div className="text-sm font-bold text-white truncate max-w-[150px]">{mastery.soulRay}</div>
                  </div>
              </div>
          </div>

          <div className="grid grid-cols-1 sm:grid-cols-3 gap-3">
            {mastery.masterQualities.map((q, i) => (
              <div key={i} className="px-4 py-3 rounded-xl bg-black/40 border border-white/5 flex items-center gap-3 text-[10px] font-black text-gray-300 uppercase transition-all hover:border-yellow-500/30 hover:bg-yellow-500/5">
                <ShieldCheck size={14} className="text-yellow-500" />
                {q}
              </div>
            ))}
          </div>

          <div className="pt-4 text-xs text-gray-500 italic leading-relaxed border-t border-white/5">
            "{mastery.mahaChohanAdvice}"
          </div>
        </div>
      </div>
    </div>
  );
};

export default SpiritualMasteryCard;
